# Site settings
author: William Lam
title: Why did you decide to study Software Engineering?
header-img: img/home-bg.png
email: teststuffreally@gmail.com
copyright_name: William Lam
description: > # this means to ignore newlines until "baseurl:"
  Software engineering with Flatiron school
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Will3240

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
